CREATE TABLE books (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			title TEXT NOT NULL DEFAULT '',
			isbn CHAR(20) UNIQUE NOT NULL DEFAULT '',
			year INTEGER NOT NULL DEFAULT 0,
			authors_id INTEGER NOT NULL DEFAULT 0,
			FOREIGN KEY (authors_id) REFERENCES authors(id)
		);